[workspace]
members = [
    "ream-parser",
    "ream-repl",
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'

[profile.dev]
opt-level = 2
debug = true
lto = false
codegen-units = 20
rpath = true
