[package]
name = "ream-parser"
version = "0.1.0"
authors = ["Bernardo Meurer <meurerbernardo@gmail.com>"]
edition = "2018"

[dependencies]
lalrpop-util = "0.16.3"
regex = "1.1.2"

[build-dependencies]
lalrpop = "0.16.3"
